Fix bug
namse/Tetris_imPental pull request #1
Opened 2021-02-25 18:23 UTC by JIIIIIND

1. 버그 발생 이유
줄 제거 이후 줄을 한 칸 내리는 부분이 포인터를 할당하는 방식으로 작성되었기 때문에 매번 한 줄 씩 t -> board[0]을 가리키는 포인터로 변하게 됩니다.
17번의 줄 제거가 이루어지고 나면 모든 줄이 t -> board[0]을 가리키는 상태이기 때문에 양 옆 4자리가 채워진 상태가 됩니다.

2. 해결 방법
포인터를 할당하는 방식이 아니라 내부의 값을 바꾸는 방식으로 변경했습니다.

2021-03-02 07:55 UTC, namse requested changes

2021-03-02 07:55 UTC, namse commented on sourceCode/tetris.c
> +        // t -> board[line - i] = t -> board[line - 1 - i];
불필요한 주석은 제거해주세요.

2021-03-02 08:21 UTC, JIIIIIND commented on sourceCode/tetris.c
> +        // t -> board[line - i] = t -> board[line - 1 - i];
주석 제거 했습니다!

2021-03-04 04:00 UTC, namse commented
@JIIIIIND 훌륭합니다! 커밋 메시지만 좀 더 규칙적(예: 항상 대문자로 시작하게)이고 어떤 작업을 했는지 잘 알 수 있도록 해주시면 좋을 것 같습니다.

2021-03-04 04:00 UTC, closed without merging